#!/bin/sh
set -e

echo "=== Deploy Shadowsocks on SnapDeploy ==="
echo ""
echo "Steps:"
echo "  1. Push to GitHub:  git push origin main"
echo "  2. Go to https://snapdeploy.dev → Sign up (no credit card)"
echo "  3. New Container → Connect your GitHub repo"
echo "  4. SnapDeploy auto-detects the Dockerfile"
echo "  5. Set env vars in dashboard:"
echo "       SSPASSWORD = yourpassword (change from default!)"
echo "       SSPORT     = 8388"
echo "  6. Click Deploy"
echo ""
echo "Your app will be at: https://<your-app>.snapdeploy.app"
echo ""
echo "Connect with: ss://YWVzLTI1Ni1nY206MTIzNDU2@<your-app>.snapdeploy.app:8388"
echo ""
echo "WARNING: Default password is 123456 — change before production!"
echo "WARNING: Free tier sleeps after inactivity (~60s wake). Upgrade to Always-On for 24/7."
