#!/bin/sh
set -e

echo "=== Deploy Shadowsocks on Render ==="
echo ""
echo "Option 1 — Blueprint (auto):"
echo "  1. Push to GitHub:  git push origin main"
echo "  2. Go to https://dashboard.render.com/blueprints"
echo "  3. Connect your repo — Render reads render.yaml automatically"
echo ""
echo "Option 2 — Manual:"
echo "  1. Push to GitHub:  git push origin main"
echo "  2. Go to https://dashboard.render.com/select-repo"
echo "  3. Pick this repo → Runtime: Docker → Name: playwithsh-ss"
echo "  4. Add env var: SSPASSWORD=yourpassword (change from default!)"
echo "  5. Deploy"
echo ""
echo "Change password later:"
echo "  Render Dashboard → Env Variables → set SSPASSWORD → manual deploy"
echo ""
echo "Connect: ss://YWVzLTI1Ni1nY206MTIzNDU2@<your-app>.onrender.com:8388"
echo ""
echo "WARNING: Default password is 123456 — always change before production!"
echo "WARNING: Render free plan spins down after inactivity — upgrade to keep 24/7."
